#!/bin/bash

# Built with MooseX::App::Plugin::BashCompletion::Command on 2017/02/13

cloudcron_COMMANDS='help deploy_queue parse'

_cloudcron_macc_help() {
    if [ $COMP_CWORD = 2 ]; then
        _cloudcron_compreply "$cloudcron_COMMANDS"
    else
        COMPREPLY=()
    fi
}

_cloudcron_macc_deploy_queue() {
    _cloudcron_compreply "--help -h --usage -?"
}

_cloudcron_macc_parse() {
    _cloudcron_compreply "--file --arn --id --prefix --help -h --usage -?"
}

_cloudcron_compreply() {
    COMPREPLY=($(compgen -W "$1" -- ${COMP_WORDS[COMP_CWORD]}))
}

_cloudcron_macc() {
    case $COMP_CWORD in
        0)
            ;;
        1)
            _cloudcron_compreply "$cloudcron_COMMANDS"
            ;;
        *)
            eval _cloudcron_macc_${COMP_WORDS[1]}

    esac
}

complete -o default -F _cloudcron_macc cloudcron


